# (slug, judul, hari materi, fase, catatan kapan/kenapa)
URUTAN = [
 ("020-M01-sql-dari-nol","M1 — SQL dari nol",7,1,"Mulai dari sini. SQL dulu, bukan Python — kamu bisa lihat hasilnya di hari pertama tanpa memasang apa pun."),
 ("021-M02-join","M2 — JOIN & data sungguhan",7,1,"Masih SQL murni. Dua minggu ini sengaja tanpa Python supaya kamu tidak berhenti sebelum mulai."),
 ("010-bekal-python","Bekal Python — dari benar-benar nol",8,1,"Sekarang, bukan nanti. Melewatinya berarti menabrak tembok di Hari 24."),
 ("022-M03-python-pandas","M3 — Python & pandas",7,1,"Bekal Python baru saja memberimu bahasanya; di sini bahasanya dipakai untuk data."),
 ("023-M04-statistik-abtest","M4 — Statistik & A/B Test",7,1,""),
 ("024-M05-visualisasi","M5 — Visualisasi Data",7,1,"Akhir fase 1. Sudah bisa dijual: merapikan data + laporan sederhana."),
 ("025-M06-sql-lanjutan","M6 — SQL Lanjutan",7,2,"Window function dan CTE. Ini prasyarat SQL Mahir dan Studi Kasus."),
 ("030-bekal-data-klien","Bekal Data Klien",6,2,"Semua modul sebelumnya memakai data rapi. Ini yang pertama memakai berkas seperti kiriman klien."),
 ("031-studi-kasus-nyata","Studi Kasus Nyata — 5 kasus",5,2,"Lanjutan langsungnya. Lima berkas berantakan dari lima jenis usaha; hasilnya boleh langsung jadi portofolio."),
 ("042-bekal-rahasia-klien","Bekal Rahasia Klien",4,2,"WAJIB sebelum klien pertama, dan sebelum M8 menyuruhmu publikasi ke Tableau Public."),
 ("040-M07-statistik-lanjutan","M7 — Statistik Lanjutan",7,2,""),
 ("041-M08-visualisasi-bi","M8 — Visualisasi Lanjutan & BI",7,2,"Akhir fase 2. Sudah bisa dijual: berkas klien dirapikan + dashboard. Titik masuk freelance sesungguhnya."),
 ("043-M09-sql-data-besar","M9 — SQL Data Besar",7,3,""),
 ("044-M10-dbt","M10 — dbt",7,3,""),
 ("045-M11-git-otomasi-streamlit","M11 — Git, Otomasi & Streamlit",7,3,""),
 ("046-bekal-kirim-hasil","Bekal Kirim Hasil",5,3,"M11 berhenti di print() dan PNG. Ini yang membuat laporannya sampai ke email klien dan berteriak kalau rusak."),
 ("047-M12-product-analytics","M12 — Product Analytics",7,3,""),
 ("048-M13-machine-learning","M13 — Machine Learning",7,3,"Akhir fase 3. Sudah bisa dijual: laporan otomatis berulang + analisis lanjutan."),
 ("050-migas-L1-fondasi-psc","Migas L1 — Fondasi blok & PSC",7,4,"Spesialisasi. Di sinilah latar KAP-mu jadi keunggulan, bukan sekadar masa lalu."),
 ("051-migas-L2-perbandingan-adil","Migas L2 — Perbandingan adil & bias",7,4,""),
 ("052-migas-L3-window-function","Migas L3 — Window function di lapangan",7,4,""),
 ("053-migas-L4-rekonsiliasi-psc","Migas L4 — Rekonsiliasi PSC",7,4,""),
 ("054-migas-L5-cadangan-keputusan","Migas L5 — Cadangan & keputusan $3 juta",7,4,"Memo Hari 35 dan grafik DCA masuk portofolio di M14."),
 ("060-M14-portofolio-cv","M14 — Portofolio & CV",7,4,""),
 ("061-M15-wawancara-lamaran","M15 — Wawancara & Lamaran",7,4,"Akhir fase 4. Siap melamar."),
 ("070-sql-mahir-L1","SQL Mahir L1 — dasar yang bolong",7,5,"Boleh ditarik maju ke sini kalau tes SQL sudah di depan mata (lihat catatan di bawah)."),
 ("071-sql-mahir-L2","SQL Mahir L2 — window function tuntas",7,5,""),
 ("072-sql-mahir-L3","SQL Mahir L3 — enam pola wawancara",7,5,"L1–L3 adalah yang diuji di live coding."),
 ("073-sql-mahir-L4","SQL Mahir L4 — kinerja & keandalan",7,5,"Yang membedakanmu dari kandidat lain yang juga bisa window function."),
 ("074-sql-mahir-L5","SQL Mahir L5 — ujian & wawancara",7,5,"Penutup. Rubrik penilaian diri ada di hari terakhir."),
 ("075-sql-produksi","SQL Produksi — kosakata database kantor",7,5,"Delapan hal yang tidak ada di SQLite: ROLLUP, QUALIFY, LATERAL, generate_series, percentile_cont, FILTER, upsert, JSON."),
 ("076-python-produksi","Python Produksi — dari notebook jadi alat",7,5,"Penutup jalur teknis: modul sendiri, pytest, dtype, vektorisasi, chunksize, logging, argparse."),
 ("062-bekal-excel-kantor","Bekal Excel Kantor",7,6,"Excel disebut di 3 dari 5 lowongan nyata; di 41 modul pengajaran: NOL sebutan rumus & pivot. Termasuk selisih Rp 3,43 miliar antara XLOOKUP dan merge."),
 ("063-bekal-alat-kantor","Bekal Alat Kantor",5,6,"Metabase 0, Looker Studio 0, Airflow 0 di kurikulum — padahal ketiganya disebut satu lowongan. DAG dibedah dengan ast, tanpa memasang Airflow."),
 ("064-bekal-bahasa-inggris","Bekal Bahasa Inggris Kerja",5,6,"Lima sebutan lewat di 41 modul. Disusun dari 639 kata lowongan sungguhan jadi 44 kata inti, plus empat jawaban wawancara."),
 ("065-menulis-untuk-manajemen","Menulis untuk Manajemen",3,6,"Executive summary: 3 sebutan di 41 modul. 40 baris tabel diringkas jadi 3 kalimat, tiap angkanya bisa ditelusuri."),
 ("077-jalur-pintu-b","Jalur Pintu B — melamar ke tempat yang tepat",3,6,"Nol dari 46 modul menyebut audit analytics. Ini menutupnya: lowongan nyata, CV, wawancara."),
 ("078-ujian-bernilai","Ujian Bernilai — 60 poin, berwaktu",2,6,"Angka objektif pertama tentang kemampuanmu. Ulangi tiga bulan lagi dan bandingkan."),
 ("079-proyek-buta","Proyek Buta — tanpa kunci jawaban",5,6,"Tiga berkas klien, tenggat nyata, nol kunci. Ditutup dengan ditinjau manusia."),
 ("085-jalur-s2-luar-negeri","Jalur S2 Luar Negeri — silabus, biaya, keputusan",7,6,"Penutup. Tujuh hari menimbang kuliah S2 di luar negeri dengan angka, bukan perasaan: silabus tujuh kampus, biaya dalam rupiah, syarat impas, dan tenggat beasiswa."),
 ("090-mat-L1-probabilitas","MAT L1 — Probabilitas formal",7,7,"Empat topik bernilai nol di 49 modul. Ini yang pertama: nilai harapan, distribusi, Bayes, teorema limit pusat. Target DATASCI W203 & ISYE 6739."),
 ("091-mat-L2-aljabar-linear","MAT L2 — Aljabar linear terapan",7,7,"Regresi diturunkan sendiri, PCA dihitung dari nol dan cocok dengan sklearn sampai 4,44e-16. Target MAST90138."),
 ("092-mat-L3-optimisasi","MAT L3 — Optimisasi numerik",7,7,"Gradient descent dari nol; aturan learning rate diturunkan, bukan dihafal. Target DSA5103 — mata kuliah yang paling sering menenggelamkan pendatang non-matematika."),
 ("093-mat-L4-deep-learning","MAT L4 — Deep learning dari nol",7,7,"Backpropagation ditulis tangan, diverifikasi 1e-11. Ditutup uji jujur: 132.609 parameter cuma unggul 4,04 poin persen atas regresi logistik. Target DSA5106 & COMP90051."),
]
FASE = {
 7: ("Bekal Matematika S2", "Menutup empat topik bernilai nol: probabilitas, aljabar linear, optimisasi, deep learning"),
 6: ("Siap diterjunkan", "Alat & bahasa yang diminta lowongan, lalu diuji: tahu ke mana melamar, punya angka objektif, dan pernah dikritik orang"),
 1: ("Fondasi", "Merapikan data & laporan sederhana"),
 2: ("Bisa dijual", "Berkas klien dirapikan + dashboard — titik masuk freelance"),
 3: ("Naik kelas", "Laporan otomatis yang sampai ke klien + analisis lanjutan"),
 4: ("Spesialisasi", "Spesialis domain migas + siap melamar kerja"),
 5: ("Mahir SQL", "Lolos tes SQL, dan tahu angkamu benar"),
}
